const story_titles = [
  "Stephen Hawking has died",
  "A Message to Our Customers",
  "Steve Jobs has passed away.",
  "Reflecting on one very, very strange year at Uber",
  "Every Google result now looks like an ad",
  "F.C.C. Repeals Net Neutrality Rules",
  "Show HN: This up votes itself",
  "Switch from Chrome to Firefox",
  "Cloudflare Reverse Proxies Are Dumping Uninitialized Memory",
  "UK votes to leave EU",
  "Tim Cook Speaks Up",
  "Announcing the first SHA-1 collision",
  "I Sell Onions on the Internet",
  "macOS High Sierra: Anyone can login as “root” with empty password",
  "SpaceX’s Falcon Heavy successfully launches",
  "Paul Allen has died",
  "Microsoft Is Said to Have Agreed to Acquire GitHub",
  "Announcing unlimited free private repos",
  "Slack’s new WYSIWYG input box is terrible",
  "Gears",
  "W3C abandons consensus, standardizes DRM, EFF resigns",
  "2048",
  "CIA malware and hacking tools",
  "Show HN: A retro video game console I've been working on in my free time",
  "Don't Fly During Ramadan",
  "IBM acquires Red Hat",
  "My Business Card Runs Linux",
  "Ask HN: Is S3 down?",
  "Linus Torvalds apologizes for his behavior, takes time off",
  "Pardon Snowden"
];

const story_srcs = [
  "http://www.bbc.com/news/uk-43396008",
  "http://www.apple.com/customer-letter/",
  "http://www.apple.com/stevejobs/",
  "https://www.susanjfowler.com/blog/2017/2/19/reflecting-on-one-very-strange-year-at-uber",
  "https://twitter.com/craigmod/status/1219644556003565568",
  "https://www.nytimes.com/2017/12/14/technology/net-neutrality-repeal-vote.html",
  "http://news.ycombinator.com/vote?for=3742902&dir=up&whence=%6e%65%77%65%73%74",
  "https://www.mozilla.org/en-US/firefox/switch/",
  "https://bugs.chromium.org/p/project-zero/issues/detail?id=1139",
  "http://www.bbc.co.uk/news/uk-politics-36615028",
  "http://www.businessweek.com/articles/2014-10-30/tim-cook-im-proud-to-be-gay",
  "https://security.googleblog.com/2017/02/announcing-first-sha1-collision.html",
  "https://www.deepsouthventures.com/i-sell-onions-on-the-internet/",
  "https://twitter.com/lemiorhan/status/935578694541770752",
  "https://techcrunch.com/2018/02/06/spacexs-historic…s/?ncid=rss&utm_source=dlvr.it&utm_medium=twitter",
  "https://www.cnbc.com/2018/10/15/microsoft-co-founder-paul-allen-dies-of-cancer-at-age-65.html",
  "http://www.bloomberg.com/news/articles/2018-06-03/…aid-to-have-agreed-to-acquire-coding-site-github?",
  "https://blog.github.com/2019-01-07-new-year-new-github/",
  "https://quuxplusone.github.io/blog/2019/11/20/slack-rich-text-box/",
  "https://ciechanow.ski/gears/",
  "https://boingboing.net/2017/09/18/antifeatures-for-all.html",
  "http://gabrielecirulli.github.io/2048/",
  "https://wikileaks.org/ciav7p1/",
  "https://internalregister.github.io/2019/03/14/Homebrew-Console.html",
  "http://varnull.adityamukerjee.net/post/59021412512/dont-fly-during-ramadan",
  "https://www.redhat.com/en/blog/red-hat-ibm-creating-leading-hybrid-cloud-provider",
  "https://www.thirtythreeforty.net/posts/2019/12/my-business-card-runs-linux/",
  "http://www.apple.com/stevejobs/",
  "https://lore.kernel.org/lkml/CA+55aFy+Hv9O5citAawS+mVZO+ywCKd9NQ2wxUmGsz9ZJzqgJQ@mail.gmail.com/",
  "https://www.pardonsnowden.org/"
];

const points = [
  "6015 points",
  "5771 points",
  "4271 points",
  "4107 points",
  "3592 points",
  "3384 points",
  "3381 points",
  "3287 points",
  "3238 points",
  "3125 points",
  "3086 points",
  "3030 points",
  "3015 points",
  "3001 points",
  "2968 points",
  "2901 points",
  "2873 points",
  "2867 points",
  "2776 points",
  "2754 points",
  "2735 points",
  "2732 points",
  "2699 points",
  "2690 points",
  "2617 points",
  "2611 points",
  "2595 points",
  "2589 points",
  "2585 points",
  "2553 points"
];

const usernames = [
  "Cogito",
  "epaga",
  "patricktomas",
  "grey-area",
  "cmod",
  "panny",
  "olalonde",
  "WisNorCan",
  "tptacek",
  "dmmalam",
  "replicatorblog",
  "pfg",
  "eightturn",
  "vladikoff",
  "mpweiher",
  "coloneltcb",
  "miguelrochefort",
  "razer6",
  "ingve",
  "robert-boehnke",
  "guelo",
  "frederfred",
  "randomname2",
  "pkiller",
  "chimeracoder",
  "nopriorarrests",
  "rcarmo",
  "iamdeedubs",
  "fejkp",
  "erlend_sh"
];

const postedOns = [
  "2 years ago",
  "4 years ago",
  "8 years ago",
  "3 years ago",
  "1 month ago",
  "2 years ago",
  "8 years ago",
  "9 months ago",
  "3 years ago",
  "4 years ago",
  "5 years ago",
  "3 years ago",
  "10 months ago",
  "2 years ago",
  "2 years ago",
  "1 year ago",
  "2 years ago",
  "1 year ago",
  "3 months ago",
  "9 days ago",
  "2 years ago",
  "6 years ago",
  "3 years ago",
  "11 months ago",
  "7 years ago",
  "1 year ago",
  "2 months ago",
  "3 years ago",
  "1 year ago",
  "3 years ago"
];

const comments = [
  "436 comments",
  "967 comments",
  "376 comments",
  "1014 comments",
  "969 comments",
  "1397 comments",
  "83 comments",
  "981 comments",
  "992 comments",
  "2531 comments",
  "974 comments",
  "485 comments",
  "435 comments",
  "813 comments",
  "872 comments",
  "277 comments",
  "1437 comments",
  "685 comments",
  "1076 comments",
  "222 comments",
  "978 comments",
  "410 comments",
  "1087 comments",
  "210 comments",
  "961 comments",
  "491 comments",
  "397 comments",
  "1055 comments",
  "996 comments",
  "781 comments"
];

const goesTos = [
  "https://news.ycombinator.com/item?id=16582136",
  "https://news.ycombinator.com/item?id=11116274",
  "https://news.ycombinator.com/item?id=3078128",
  "https://news.ycombinator.com/item?id=13682022",
  "https://news.ycombinator.com/item?id=22107823",
  "https://news.ycombinator.com/item?id=15924794",
  "https://news.ycombinator.com/item?id=3742902",
  "https://news.ycombinator.com/item?id=20052623",
  "https://news.ycombinator.com/item?id=13718752",
  "https://news.ycombinator.com/item?id=11966167",
  "https://news.ycombinator.com/item?id=6201586",
  "https://news.ycombinator.com/item?id=21190265",
  "https://news.ycombinator.com/item?id=20260863",
  "https://news.ycombinator.com/item?id=18138328",
  "https://news.ycombinator.com/item?id=12707606",
  "https://news.ycombinator.com/item?id=21401973",
  "https://news.ycombinator.com/item?id=19109474",
  "https://news.ycombinator.com/item?id=22050802",
  "https://news.ycombinator.com/item?id=12073675",
  "https://news.ycombinator.com/item?id=8595905",
  "https://news.ycombinator.com/item?id=19632449",
  "https://news.ycombinator.com/item?id=18064537",
  "https://news.ycombinator.com/item?id=16619917",
  "https://news.ycombinator.com/item?id=18052923",
  "https://news.ycombinator.com/item?id=16065845",
  "https://news.ycombinator.com/item?id=3288671",
  "https://news.ycombinator.com/item?id=21611677",
  "https://news.ycombinator.com/item?id=22236106",
  "https://news.ycombinator.com/item?id=19719380",
  "https://news.ycombinator.com/item?id=15316175"
];

const posts = story_titles.map((title, index) => {
  return {
    title: title,
    source: `(${story_srcs[index]})`,
    points: points[index],
    username: usernames[index],
    postedOn: postedOns[index],
    comments: comments[index],
    goesTo: goesTos[index]
  };
})

export default posts;

